geonames:
  countryInfo:
    url: http://api.geonames.org/countryInfo?type=json&username=pradamsjr
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3000/globe
    driverName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

